<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

Route::get('/subscribe', function () {

    /*
     * subscriptions need to use stripe setup intents API to securely gather the customer's payment method details
     * it tells stripe the intention to charge a customer's payment method
     */

    return view('subscribe', [
         'intent' => auth()->user()->createSetupIntent()
    ]);
})->middleware(['auth'])->name('subscribe.index');

Route::post('/subscribe', function (Request $request) {

    /*
     * plan and paymentMethod will both be coming from the intent using the createSetupIntent() method
     * Create the payment method for stripe for a subscription.
     * internal_name_product of product should be stored in database.
     */
    $request->user()->newSubscription(
        'internal_name_product ', $request->plan
    )->create($request->paymentMethod);

    return redirect()->route('subscribe.index')->with(['success' => 'Payment made']);
})->middleware(['auth'])->name('subscribe.store');

Route::get('/life', function () {
    return view('life');
})->middleware(['auth'])->name('life.index');

Route::post('/life', function (Request $request) {

    /*
    * the hidden paymentMethod.id generated by the createPaymentMethod()
    * no new customer is created over at stripe but can be achieved with their api
    */
    auth()->user()->charge(49900, $request->paymentMethod, [
        'currency' => 'gbp'
    ]);

    return redirect()->route('life.index')->with(['success' => 'Payment made']);
})->middleware(['auth'])->name('life.store');


require __DIR__.'/auth.php';
